---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exit-node.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "exit-node.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{- with .Values.tailscale.loginServer }}
  TS_LOGIN_SERVER: {{ . | b64enc }}
  {{- end }}
  TS_AUTHKEY: {{ (required "Please set a tailscale preAuthkey via --set tailscale.preAuthKey=<key> or in values.yaml" .Values.tailscale.preAuthKey) | b64enc }}
{{- if eq .Values.tailscale.state.type "Secret" }}
  TS_KUBE_SECRET: {{ include "exit-node.tailscale.state.name" . | b64enc }}
{{- end }}
  wg0.conf: {{ (required "Please set a wireguard config via --set-file tailguard.wireguardConfig=wg0.conf or in values.yaml as a string literal" .Values.tailguard.wireguardConfig) | b64enc }}
